'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var QUERY_MAP = 'QUERY_MAP';
exports.QUERY_MAP = QUERY_MAP;
var TABLE_VISIBLE_ROWS_CHANGE_MAP = 'TABLE_VISIBLE_ROWS_CHANGE_MAP';
exports.TABLE_VISIBLE_ROWS_CHANGE_MAP = TABLE_VISIBLE_ROWS_CHANGE_MAP;
var CHANGE_BOUNDS_MAP = 'CHANGE_BOUNDS_MAP';
exports.CHANGE_BOUNDS_MAP = CHANGE_BOUNDS_MAP;
var TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP = 'TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP';
exports.TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP = TABLE_HOVERED_ROWS_INDEX_CHANGE_MAP;
var MARKER_HOVER_INDEX_CHANGE_MAP = 'MARKER_HOVER_INDEX_CHANGE_MAP';
exports.MARKER_HOVER_INDEX_CHANGE_MAP = MARKER_HOVER_INDEX_CHANGE_MAP;
var SHOW_BALLON_MAP = 'SHOW_BALLON_MAP';
exports.SHOW_BALLON_MAP = SHOW_BALLON_MAP;